<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnimalHealthcare.Data.Models\AnimalHealthcare.Data.Models.csproj" />
    <ProjectReference Include="..\AnimalHealthcare.GCommon\AnimalHealthcare.GCommon.csproj" />
    <ProjectReference Include="..\AnimalHealthcare.Services.AutoMapping\AnimalHealthcare.AutoMapping.csproj" />
  </ItemGroup>

</Project>
