// <auto-generated />
using System;
using AnimalHealthcare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalHealthcare.Data.Migrations
{
    [DbContext(typeof(AnimalHealthcareDbContext))]
    [Migration("20250628063500_RemoveAnimalDoctorRelationship")]
    partial class RemoveAnimalDoctorRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimalHealthcare.Data.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 4,
                            Breed = "Labrador Retriever",
                            Gender = "Male",
                            IsDeleted = false,
                            Name = "Buddy",
                            Species = "Dog",
                            UserProfileId = "28d4fc17-fdaf-4dc5-9bb3-5cc0b4c64bc2"
                        },
                        new
                        {
                            Id = 2,
                            Age = 3,
                            Breed = "Siamese",
                            Gender = "Female",
                            IsDeleted = false,
                            Name = "Whiskers",
                            Species = "Cat",
                            UserProfileId = "28d4fc17-fdaf-4dc5-9bb3-5cc0b4c64bc2"
                        });
                });

            modelBuilder.Entity("AnimalHealthcare.Data.Models.AnimalClinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("AnimalClinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, Springfield",
                            ImageUrl = "/images/clinics/happy-paws.jpg",
                            Name = "Happy Paws Veterinary Clinic",
                            PhoneNumber = "555-1234"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St, Shelbyville",
                            ImageUrl = "/images/clinics/healthy-tails-animal-hospital.jpg",
                            Name = "Healthy Tails Animal Hospital",
                            PhoneNumber = "555-5678"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Oak Ave, Capital City",
                            ImageUrl = "/images/clinics/gentle-care-pet-clinic.jpg",
                            Name = "Gentle Care Pet Clinic",
                            PhoneNumber = "555-9012"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Maple Rd, Ogdenville",
                            ImageUrl = "/images/clinics/purrfect-health-vet-center.jpg",
                            Name = "Purrfect Health Vet Center",
                            PhoneNumber = "555-3456"
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Pine St, North Haverbrook",
                            ImageUrl = "/images/clinics/four-legged-friends-vet.jpeg",
                            Name = "Four-Legged Friends Vet",
                            PhoneNumber = "555-7890"
                        });
                });

            modelBuilder.Entity("AnimalHealthcare.Data.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ProcedureId")
                        .HasColumnType("int");

                    b.Property<string>("UserProfileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ProcedureId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("AnimalHealthcare.Data.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalClinicId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalClinicId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalClinicId = 1,
                            ImageUrl = "/images/doctors/sarah-smith.jpg",
                            IsDeleted = false,
                            Name = "Dr. Sarah Smith",
                            PhoneNumber = "555-1001",
                            Specialization = "Surgery",
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 2,
                            AnimalClinicId = 1,
                            ImageUrl = "/images/doctors/james-brown.jpg",
                            IsDeleted = false,
                            Name = "Dr. James Brown",
                            PhoneNumber = "555-1002",
                            Specialization = "Dentistry",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 3,
                            AnimalClinicId = 1,
                            ImageUrl = "/images/doctors/laura-green.jpg",
                            IsDeleted = false,
                            Name = "Dr. Laura Green",
                            PhoneNumber = "555-1003",
                            Specialization = "Dermatology",
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 4,
                            AnimalClinicId = 1,
                            ImageUrl = "/images/doctors/mark-white.jpg",
                            IsDeleted = false,
                            Name = "Dr. Mark White",
                            PhoneNumber = "555-1004",
                            Specialization = "Radiology",
                            YearsOfExperience = 9
                        },
                        new
                        {
                            Id = 5,
                            AnimalClinicId = 2,
                            ImageUrl = "/images/doctors/olivia-wilson.jpg",
                            IsDeleted = false,
                            Name = "Dr. Olivia Wilson",
                            PhoneNumber = "555-1005",
                            Specialization = "Cardiology",
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 6,
                            AnimalClinicId = 2,
                            ImageUrl = "/images/doctors/daniel-martinez.jpg",
                            IsDeleted = false,
                            Name = "Dr. Daniel Martinez",
                            PhoneNumber = "555-1006",
                            Specialization = "Neurology",
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = 7,
                            AnimalClinicId = 2,
                            ImageUrl = "/images/doctors/emma-clark.jpg",
                            IsDeleted = false,
                            Name = "Dr. Emma Clark",
                            PhoneNumber = "555-1007",
                            Specialization = "Ophthalmology",
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 8,
                            AnimalClinicId = 3,
                            ImageUrl = "/images/doctors/michael-lee.jpg",
                            IsDeleted = false,
                            Name = "Dr. Michael Lee",
                            PhoneNumber = "555-1008",
                            Specialization = "Orthopedics",
                            YearsOfExperience = 11
                        },
                        new
                        {
                            Id = 9,
                            AnimalClinicId = 3,
                            ImageUrl = "/images/doctors/sophia-garcia.jpg",
                            IsDeleted = false,
                            Name = "Dr. Sophia Garcia",
                            PhoneNumber = "555-1009",
                            Specialization = "Oncology",
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 10,
                            AnimalClinicId = 3,
                            ImageUrl = "/images/doctors/liam-king.jpg",
                            IsDeleted = false,
                            Name = "Dr. Liam King",
                            PhoneNumber = "555-1010",
                            Specialization = "Endocrinology",
                            YearsOfExperience = 4
                        },
                        new
                        {
                            Id = 11,
                            AnimalClinicId = 4,
                            ImageUrl = "/images/doctors/william-johnson.jpg",
                            IsDeleted = false,
                            Name = "Dr. William Johnson",
                            PhoneNumber = "555-1011",
                            Specialization = "Emergency Medicine",
                            YearsOfExperience = 13
                        },
                        new
                        {
                            Id = 12,
                            AnimalClinicId = 4,
                            ImageUrl = "/images/doctors/mia-hernandez.jpg",
                            IsDeleted = false,
                            Name = "Dr. Mia Hernandez",
                            PhoneNumber = "555-1012",
                            Specialization = "General Practice",
                            YearsOfExperience = 4
                        },
                        new
                        {
                            Id = 13,
                            AnimalClinicId = 5,
                            ImageUrl = "/images/doctors/ethan-robinson.jpg",
                            IsDeleted = false,
                            Name = "Dr. Ethan Robinson",
                            PhoneNumber = "555-1013",
                            Specialization = "Pediatrics",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 14,
                            AnimalClinicId = 5,
                            ImageUrl = "/images/doctors/isabella-lopez.jpg",
                            IsDeleted = false,
                            Name = "Dr. Isabella Lopez",
                            PhoneNumber = "555-1014",
                            Specialization = "Geriatrics",
                            YearsOfExperience = 6
                        });
                });

            modelBuilder.Entity("AnimalHealthcare.Data.Models.DoctorProcedure", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId", "ProcedureId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("DoctorProcedures");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            ProcedureId = 3
                        },
                        new
                        {
                            DoctorId = 1,
                            ProcedureId = 10
                        },
                        new
                        {
                            DoctorId = 1,
                            ProcedureId = 16
                        },
                        new
                        {
                            DoctorId = 2,
                            ProcedureId = 2
                        },
                        new
                        {
                            DoctorId = 3,
                            ProcedureId = 9
                        },
                        new
                        {
                            DoctorId = 3,
                            ProcedureId = 11
                        },
                        new
                        {
                            DoctorId = 4,
                            ProcedureId = 5
                        },
                        new
                        {
                            DoctorId = 4,
                            ProcedureId = 7
                        },
                        new
                        {
                            DoctorId = 5,
                            ProcedureId = 8
                        },
                        new
                        {
                            DoctorId = 5,
                            ProcedureId = 6
                        },
                        new
                        {
                            DoctorId = 6,
                            ProcedureId = 21
                        },
                        new
                        {
                            DoctorId = 7,
                            ProcedureId = 12
                        },
                        new
                        {
                            DoctorId = 8,
                            ProcedureId = 10
                        },
                        new
                        {
                            DoctorId = 9,
                            ProcedureId = 16
                        },
                        new
                        {
                            DoctorId = 10,
                            ProcedureId = 6
                        },
                        new
                        {
                            DoctorId = 11,
                            ProcedureId = 20
                        },
                        new
                        {
                            DoctorId = 11,
                            ProcedureId = 15
                        },
                        new
                        {
                            DoctorId = 12,
                            ProcedureId = 1
                        },
                        new
                        {
                            DoctorId = 12,
                            ProcedureId = 4
                        },
                        new
                        {
                            DoctorId = 12,
                            ProcedureId = 13
                        },
                        new
                        {
                            DoctorId = 12,
                            ProcedureId = 14
                        },
                        new
                        {
                            DoctorId = 13,
                            ProcedureId = 1
                        },
                        new
                        {
                            DoctorId = 13,
                            ProcedureId = 18
                        },
                        new
                        {
                            DoctorId = 14,
                            ProcedureId = 19
                        },
                        new
                        {
                            DoctorId = 14,
                            ProcedureId = 17
                        });
                });

            modelBuilder.Entity("AnimalHealthcare.Data.Models.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Procedures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Routine animal vaccination",
                            IsDeleted = false,
                            Name = "Vaccination"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Professional dental cleaning for pets",
                            IsDeleted = false,
                            Name = "Dental Cleaning"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Spaying or neutering surgery",
                            IsDeleted = false,
                            Name = "Spay/Neuter"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Microchip implantation for ID",
                            IsDeleted = false,
                            Name = "Microchipping"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Standard diagnostic X-ray",
                            IsDeleted = false,
                            Name = "X-Ray"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Routine blood analysis",
                            IsDeleted = false,
                            Name = "Blood Test"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Abdominal ultrasound exam",
                            IsDeleted = false,
                            Name = "Ultrasound"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Testing for heartworm disease",
                            IsDeleted = false,
                            Name = "Heartworm Test"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Skin or blood allergy tests",
                            IsDeleted = false,
                            Name = "Allergy Testing"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Surgery for bone/joint issues",
                            IsDeleted = false,
                            Name = "Orthopedic Surgery"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Collection and analysis of skin sample",
                            IsDeleted = false,
                            Name = "Skin Biopsy"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Comprehensive eye examination",
                            IsDeleted = false,
                            Name = "Eye Exam"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Professional ear cleaning",
                            IsDeleted = false,
                            Name = "Ear Cleaning"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Treatment for internal/external parasites",
                            IsDeleted = false,
                            Name = "Parasite Treatment"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Treatment and bandaging of wounds",
                            IsDeleted = false,
                            Name = "Wound Care"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Surgical tumor removal",
                            IsDeleted = false,
                            Name = "Tumor Removal"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Consultation for behavioral issues",
                            IsDeleted = false,
                            Name = "Behavioral Consultation"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Trimming of nails/claws",
                            IsDeleted = false,
                            Name = "Nail Trim"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Basic grooming service",
                            IsDeleted = false,
                            Name = "Grooming"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Immediate emergency treatment",
                            IsDeleted = false,
                            Name = "Emergency Care"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Specialized consultation for neurological conditions",
                            IsDeleted = false,
                            Name = "Neurological Consultation"
                        });
                });

            modelBuilder.Entity("AnimalHealthcare.Data.Models.UserProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = "28d4fc17-fdaf-4dc5-9bb3-5cc0b4c64bc2",
                            Address = "123 Admin St, Admin City, Admin Country",
                            FullName = "Admin User",
                            IsDeleted = false,
                            PhoneNumber = "123-456-7890",
                            ProfilePictureUrl = "/images/profiles/admin.jpg"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "28d4fc17-fdaf-4dc5-9bb3-5cc0b4c64bc2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "22222222-2222-2222-2222-222222222222",
                            Email = "admin@animalhealthcare.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ANIMALHEALTHCARE.COM",
                            NormalizedUserName = "ADMIN@ANIMALHEALTHCARE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBmKoup3TJhw47bvcqlUwPabiIwPFZOLI7qc46/vZm2L+gLbHeatMyc2TEcT+t/Hjw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "11111111-1111-1111-1111-111111111111",
                            TwoFactorEnabled = false,
                            UserName = "admin@animalhealthcare.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AnimalHealthcare.Data.Models.Animal", b =>
                {
                    b.HasOne("AnimalHealthcare.Data.Models.UserProfile", "UserProfile")
                        .WithMany("Animals")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("AnimalHealthcare.Data.Models.Appointment", b =>
                {
                    b.HasOne("AnimalHealthcare.Data.Models.Animal", "Animal")
                        .WithMany("Appointments")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimalHealthcare.Data.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimalHealthcare.Data.Models.Procedure", "Procedure")
                        .WithMany()
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnimalHealthcare.Data.Models.UserProfile", "UserProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Doctor");

                    b.Navigation("Procedure");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("AnimalHealthcare.Data.Models.Doctor", b =>
                {
                    b.HasOne("AnimalHealthcare.Data.Models.AnimalClinic", "AnimalClinic")
                        .WithMany("Doctors")
                        .HasForeignKey("AnimalClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnimalClinic");
                });

            modelBuilder.Entity("AnimalHealthcare.Data.Models.DoctorProcedure", b =>
                {
                    b.HasOne("AnimalHealthcare.Data.Models.Doctor", "Doctor")
                        .WithMany("DoctorProcedures")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalHealthcare.Data.Models.Procedure", "Procedure")
                        .WithMany("DoctorProcedures")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("AnimalHealthcare.Data.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithOne()
                        .HasForeignKey("AnimalHealthcare.Data.Models.UserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimalHealthcare.Data.Models.Animal", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("AnimalHealthcare.Data.Models.AnimalClinic", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("AnimalHealthcare.Data.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorProcedures");
                });

            modelBuilder.Entity("AnimalHealthcare.Data.Models.Procedure", b =>
                {
                    b.Navigation("DoctorProcedures");
                });

            modelBuilder.Entity("AnimalHealthcare.Data.Models.UserProfile", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
